name: assign_issue_number_to_pr_body

on:
  pull_request:
    types: [opened]
    branches-ignore:
      - develop

permissions:
  contents: read
  pull-requests: write

jobs:
  append_issue_number_to_pr_body:
    runs-on: ubuntu-latest
    steps:
      - name: append feature number to PR body
        uses: actions/github-script@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number
            });
            const body = pr.data.body;
            const issueNumber= pr.data.head.ref.split('-')[1];
            const newBody = body + "\n\n" + "연관된 issue: #" + issueNumber;
            await github.pulls.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  body: newBody
              });
