name: assign_issue_number_to_pr_body

on:
  pull_request:
    types: [opened]
    branches-ignore:
      - develop

permissions:
  contents: read
  pull-requests: write

jobs:
  append_issue_number_to_pr_body:
    runs-on: ubuntu-latest
    steps:
      - name: append feature number to PR body
        uses: actions/github-script@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const body = pr.data.body || '';
            const branchName = pr.data.head.ref;

            // 브랜치명에서 이슈번호 추출 (예: feat-123)
            const parts = branchName.split('-');
            const issueNumber = parts.length > 1 ? parts[1] : null;

            if (!issueNumber) {
              console.log("이슈 번호를 브랜치명에서 찾을 수 없습니다.");
              return;
            }

            const newBody = body.includes(`Closes #${issueNumber}`)
              ? body // 이미 있으면 그대로
              : `Closes #${issueNumber}\n\n${body}`;

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body: newBody
            });
